services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: next
      POSTGRES_PASSWORD: 1qaz2wsx
      POSTGRES_DB: next
    ports:
      - "5432:5432"
    volumes:
      - next_ai_cr_test_data:/var/lib/postgresql/data

volumes:
  next_ai_cr_test_data:
